public enum CustomizationSlot
{
    FRONT_HAIR,
    BACK_HAIR,
    SIDE_HAIR,
    HAIR_COLOR,
    UPPER_CLOTHES,
    LOWER_CLOTHES,
    SKIN_COLOR,
    EYE_COLOR,
    EYE_SHAPE,
    ACCESSORIES,
    ACCESSORIES_COLOR
}